import { BaseApiService } from '../base';
import type { ApiResponse, Address } from '../../../common/interfaces';

export interface CreateAddressRequest {
    type: 'HOME' | 'WORK' | 'OTHER';
    addressLine1: string;
    addressLine2?: string;
    city: string;
    state: string;
    country: string;
    postalCode?: string;
    isDefault: boolean;
}

export interface UpdateAddressRequest extends Partial<CreateAddressRequest> {
    id: string;
}

export interface AddressListResponse {
    addresses: Address[];
    count: number;
    hasDefault: boolean;
}

export class AddressService extends BaseApiService {
    constructor() {
        super('/booking'); // Address endpoints are under booking routes
    }

    /**
     * Get user addresses for booking selection
     */
    async getAddressesForBooking(): Promise<ApiResponse<AddressListResponse>> {
        return this.get<AddressListResponse>('/addresses');
    }

    /**
     * Create a new address
     */
    async createAddress(data: CreateAddressRequest): Promise<ApiResponse<Address>> {
        // Since there's no dedicated address endpoint, we'll use the user profile update
        // This is a workaround until dedicated address endpoints are created
        const userService = await import('./user');

        // Get current profile to append new address
        const profileResponse = await userService.userService.getProfile();
        if (!profileResponse.success || !profileResponse.data) {
            throw new Error('Failed to get current profile');
        }

        const currentAddresses = profileResponse.data.addresses || [];

        // If this is set as default, unset other defaults
        const updatedAddresses = data.isDefault
            ? currentAddresses.map(addr => ({ ...addr, isDefault: false }))
            : currentAddresses;

        // Add new address
        updatedAddresses.push({
            ...data,
            id: undefined, // Will be generated by backend
        } as Address);

        // Update profile with new addresses
        const updateResponse = await userService.userService.updateProfile({
            addresses: updatedAddresses
        });

        if (!updateResponse.success || !updateResponse.data) {
            throw new Error('Failed to create address');
        }

        // Return the newly created address
        const newAddress = updateResponse.data.addresses?.find(addr =>
            addr.addressLine1 === data.addressLine1 &&
            addr.city === data.city &&
            addr.state === data.state
        );

        return {
            success: true,
            message: 'Address created successfully',
            data: newAddress!
        };
    }

    /**
     * Update an existing address
     */
    async updateAddress(data: UpdateAddressRequest): Promise<ApiResponse<Address>> {
        const userService = await import('./user');

        // Get current profile
        const profileResponse = await userService.userService.getProfile();
        if (!profileResponse.success || !profileResponse.data) {
            throw new Error('Failed to get current profile');
        }

        const currentAddresses = profileResponse.data.addresses || [];

        // Find and update the address
        const updatedAddresses = currentAddresses.map(addr => {
            if (addr.id === data.id) {
                const updatedAddr = { ...addr, ...data };

                // If this is set as default, unset other defaults
                if (data.isDefault) {
                    return updatedAddr;
                }
                return updatedAddr;
            }

            // If the updated address is set as default, unset this one
            if (data.isDefault) {
                return { ...addr, isDefault: false };
            }

            return addr;
        });

        // Update profile with modified addresses
        const updateResponse = await userService.userService.updateProfile({
            addresses: updatedAddresses
        });

        if (!updateResponse.success || !updateResponse.data) {
            throw new Error('Failed to update address');
        }

        // Return the updated address
        const updatedAddress = updateResponse.data.addresses?.find(addr => addr.id === data.id);

        return {
            success: true,
            message: 'Address updated successfully',
            data: updatedAddress!
        };
    }

    /**
     * Delete an address
     */
    async deleteAddress(addressId: string): Promise<ApiResponse<void>> {
        const userService = await import('./user');

        // Get current profile
        const profileResponse = await userService.userService.getProfile();
        if (!profileResponse.success || !profileResponse.data) {
            throw new Error('Failed to get current profile');
        }

        const currentAddresses = profileResponse.data.addresses || [];

        // Remove the address
        const updatedAddresses = currentAddresses.filter(addr => addr.id !== addressId);

        // Update profile with remaining addresses
        const updateResponse = await userService.userService.updateProfile({
            addresses: updatedAddresses
        });

        if (!updateResponse.success) {
            throw new Error('Failed to delete address');
        }

        return {
            success: true,
            message: 'Address deleted successfully',
            data: undefined
        };
    }

    /**
     * Set an address as default
     */
    async setDefaultAddress(addressId: string): Promise<ApiResponse<Address>> {
        const userService = await import('./user');

        // Get current profile
        const profileResponse = await userService.userService.getProfile();
        if (!profileResponse.success || !profileResponse.data) {
            throw new Error('Failed to get current profile');
        }

        const currentAddresses = profileResponse.data.addresses || [];

        // Update addresses to set new default
        const updatedAddresses = currentAddresses.map(addr => ({
            ...addr,
            isDefault: addr.id === addressId
        }));

        // Update profile with modified addresses
        const updateResponse = await userService.userService.updateProfile({
            addresses: updatedAddresses
        });

        if (!updateResponse.success || !updateResponse.data) {
            throw new Error('Failed to set default address');
        }

        // Return the updated default address
        const defaultAddress = updateResponse.data.addresses?.find(addr => addr.id === addressId);

        return {
            success: true,
            message: 'Default address updated successfully',
            data: defaultAddress!
        };
    }
}

export const addressService = new AddressService();